#!/bin/bash

set -xe

mkdir -p /root/.m2/repository
cp -r /app/m2/* /root/.m2/repository/

cd demo-out-repo
./mvnw clean package
#./mvnw -Dmaven.repo.local=/app/m2 clean package

cd ../out-repo
shopt -s dotglob

mv -f ../demo-out-repo/* ./
ls -al ./target
mkdir -p output
mv ./target/*.jar ./output/"$BUILD_JAR_NAME"


git config --global user.email "${git-email}"
git config --global user.name "${git-name}"

git status
git add .
git commit -m "[ci skip] pushing jar for demo"