#!/bin/bash

set -xe

cd articulate-ci-demo
#./mvnw package -Dmaven.test.skip=true -Dmaven.repo.local=../m2/rootfs/opt/m2
pwd
find ../../
ls -al ../
ls -al
mkdir -p target
echo "test" >> output/articulate-0.0.1-SNAPSHOT.jar
pwd
find .


cd ../out-repo
shopt -s dotglob
mv -f ../articulate-ci-demo/* ./

##mkdir -p /root/.ssh/
#touch /root/.ssh/known_hosts

#ssh-keyscan github.com >> ~/.ssh/known_hosts

git config --global user.email "${git-email}"
git config --global user.name "${git-name}"
#git pull origin test
git status
git add .
git commit -m "[ci skip] artifactory"