#!/bin/bash

set -xe

pwd
env


cf api $PWS_API --skip-ssl-validation

cf login -u $PWS_USER -p $PWS_PWD -o "$PWS_ORG" -s "$PWS_SPACE"

cf apps

set +e
main_app_exist=$(cf apps | grep "canary-" | grep "canary-main" | wc -l)
main_instance_count=1
if [ $main_app_exist -gt 1 ]
then
 main_instance_count=$(cf apps | grep "canary-" | grep "canary-main" | grep -v "vernarable" | awk -F"/" '{print $2} ' |awk '{print $1}')
fi

echo $main_instance_count > ./current-app-info/next-app-instance-count.txt
set -xe
echo "New version of app to be deployed to instance-count $(cat ./current-app-info/next-app-instance-count.txt)"

