#!/bin/bash

set -xe

cd articulate-ci-demo
#./mvnw package -Dmaven.test.skip=true -Dmaven.repo.local=../m2/rootfs/opt/m2
pwd
find ../../
ls -al ../
ls -al
touch output/testfilexxx
pwd
find .


cd ../out
shopt -s dotglob
mv -f ../articulate-ci-demo/* ./
git config --global user.email "${git-email}"
git config --global user.name "${git-name}"
git status
git add .
git commit -m "test"