#!/bin/bash

set -xe

cd articulate-ci-demo
#./mvnw package -Dmaven.test.skip=true -Dmaven.repo.local=../m2/rootfs/opt/m2
pwd
find ../../
ls -al ../
ls -al
touch output/testfile
pwd
find .


cd ../out
shopt -s dotglob
mv -f ../articulate-ci-demo/* ./
git config --global user.email "${git_email}"
git config --global user.name "${git_name}"
git status
git merge --no-edit test/test