#!/bin/bash

set -xe

pwd
env

cf api $PWS_API --skip-ssl-validation

cf login -u $PWS_USER -p $PWS_PWD -o "$PWS_ORG" -s "$PWS_SPACE"

cf apps

cf routes

export PWS_DOMAIN_NAME=$PWS_APP_DOMAIN
export MAIN_ROUTE_HOSTNAME=canary-main-$PWS_APP_SUFFIX
export MAIN_APP_HOSTNAME=canary-main-$PWS_APP_SUFFIX

export STAGING_ROUTE_HOSTNAME=canary-staging-$PWS_APP_SUFFIX
export STAGING_APP_HOSTNAME=canary-staging-$PWS_APP_SUFFIX
export STAGING_APP_INSTANCE_COUNT=$(cat ./current-app-info/next-app-instance-count.txt)

export VERNARABLE_APP_HOSTNAME=canary-main-$PWS_APP_SUFFIX-vernarable

echo "scaling staging instance to $STAGING_APP_INSTANCE_COUNT prior to promote to $MAIN_APP_HOSTNAME"
cf scale $STAGING_APP_HOSTNAME -i $STAGING_APP_INSTANCE_COUNT

vernarable_app_exist=$(cf apps | grep "$VERNARABLE_APP_HOSTNAME" | wc -l)
if [ $vernarable_app_exist -eq 1 ]
then
	cf delete $VERNARABLE_APP_HOSTNAME -f
fi

echo "Mapping route and rename"
main_app_exist=$(cf apps | grep "$MAIN_APP_HOSTNAME" | wc -l)
staging_app_exist=$(cf apps | grep "$STAGING_APP_HOSTNAME" | wc -l)


if [ $main_app_exist -eq 0 ] && [ $staging_app_exist -eq 1 ] 
then
echo "only staging app exist. staging app promotes to main app "
cf map-route $STAGING_APP_HOSTNAME $PWS_DOMAIN_NAME --hostname $MAIN_ROUTE_HOSTNAME
cf unmap-route $STAGING_APP_HOSTNAME $PWS_DOMAIN_NAME --hostname $STAGING_ROUTE_HOSTNAME
cf rename $STAGING_APP_HOSTNAME $MAIN_APP_HOSTNAME
elif [ $main_app_exist -eq 1 ] && [ $staging_app_exist -eq 1 ] 
then
echo "both staging and main app exists. staging app promotes to main app with the same instance count of existing main account"
echo "main app turns into vernable app with stop process and unmap routes."
echo "existing vernarable app will be removed"

cf map-route $STAGING_APP_HOSTNAME $PWS_DOMAIN_NAME --hostname $MAIN_ROUTE_HOSTNAME
cf unmap-route $STAGING_APP_HOSTNAME $PWS_DOMAIN_NAME --hostname $STAGING_ROUTE_HOSTNAME
cf unmap-route $MAIN_APP_HOSTNAME $PWS_DOMAIN_NAME --hostname $MAIN_ROUTE_HOSTNAME
cf rename $MAIN_APP_HOSTNAME $MAIN_APP_HOSTNAME-vernarable
cf stop $VERNARABLE_APP_HOSTNAME 
cf rename $STAGING_APP_HOSTNAME $MAIN_APP_HOSTNAME

fi

echo "Mapping route and rename done."
cf routes
cf apps

