#!/bin/bash

set -xe

pwd
env

cf api $PWS_API --skip-ssl-validation

cf login -u $PWS_USER -p $PWS_PWD -o "$PWS_ORG" -s "$PWS_SPACE"

cf apps

cf routes

export PWS_DOMAIN_NAME=$PWS_APP_DOMAIN
export MAIN_ROUTE_HOSTNAME=canary-main-$PWS_APP_SUFFIX
export MAIN_APP_HOSTNAME=canary-$PWS_APP_SUFFIX

export STAGING_APP_HOSTNAME=canary-staging-$PWS_APP_SUFFIX
export STAGING_APP_INSTANCE_COUNT=$(cat ./current-app-info/next-app-instance-count.txt)

echo "scaling staging instance to $STAGING_APP_INSTANCE_COUNT "
for (( i=2 ;i < $STAGING_APP_INSTANCE_COUNT ; i++ )) {
 cf scale $STAGING_APP_HOSTNAME -i $i
}


echo "Mapping main app route to point to $STAGING_APP_HOSTNAME instance"
cf map-route $STAGING_APP_HOSTNAME $PWS_DOMAIN_NAME --hostname $MAIN_ROUTE_HOSTNAME

cf routes

echo "Removing previous main app route that pointed to $MAIN_APP_HOSTNAME instance"
set +e
cf unmap-route $MAIN_APP_HOSTNAME $PWS_DOMAIN_NAME --hostname $MAIN_ROUTE_HOSTNAME
set -e
echo "Routes updated"

echo "rename app $MAIN_APP_HOSTNAME to vernerable"
cf rename $MAIN_APP_HOSTNAME $MAIN_APP_HOSTNAME-vernarable
cf rename $STAGING_APP_HOSTNAME $MAIN_APP_HOSTNAME
echo "App name updated"

cf routes
